version: '3.9'

services:
  db:
    image: timescale/timescaledb:2.5.0-pg12
    command: ["postgres", "-c", "log_statement=all"]
    shm_size: 1g
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: "pylonboard_user"
      POSTGRES_PASSWORD: "pylonboard_user_pass"
      POSTGRES_MULTIPLE_DATABASES: pylonboard
    volumes:
      - .docker/postgres/init:/docker-entrypoint-initdb.d
      - .docker/postgres/data:/var/lib/postgresql/data
  
  redis:
    image: redis:4
    ports:
      - "35433:6379"

  logging:
    image: datalust/seq:5.1
    ports:
      - "35435:80"
    environment:
      ACCEPT_EULA: "Y"

